version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: chitakov
      POSTGRES_PASSWORD: chitakov123
      POSTGRES_DB: SecureAccessApp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db-data:
